db:
  host: ""
  port:
  user: ""
  password: ""
  name: ""
  driver: ""

jwt:
  secret_key: ""
  access_token_expire_minutes:
  refresh_token_expire_days:
  algorithm: ""

openai:
  api_key: ""
  model: ""
  url: ""
  instruction: ""

