db:
  host: ""
  port:
  user: ""
  password: ""
  name: ""
  driver: ""

jwt:
  secret_key: ""
  access_token_expire_minutes:
  refresh_token_expire_days:
  algorithm: ""

openai:
  api_key: ""
  model: ""
  url: ""
  instruction: ""

azure_speech:
  azure_key: ""
  azure_region: ""

heygen:
  api_key: "N2FjOGZmOTVmNWY0NGIzZjg4MWE4MThhYmEzZDY4ZWEtMTc0MDQ5MTE0Ng"
  base_url: "https://api.heygen.com/v2"
  avatar_id: "your-fixed-avatar-id"
  voice_id: "your-fixed-voice-id"